spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opensource_project_team6?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jh327900@
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, email, profile
            #redirect-uri: ${REDIRECT_URL}
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create


jwt:
  secret: my-very-secret-jwt-key
  expiration: 3600000
  
logging:
  level:
    org.hibernate.SQL: debug # jpa나 hibernate가 생성하는 로그가 보임 (로그를 통해서 보임)