spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opensourse_project_team6?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jh327900@

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug # jpa나 hibernate가 생성하는 로그가 보임 (로그를 통해서 보임)